name: zimfarmlink
description: A smart farming coordination app for Zimbabwean agriculture.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.0
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  speech_to_text: ^6.4.0
  flutter_tts: ^3.6.3
  # ✅ Added Supabase for cloud DB (web + mobile safe)
  supabase_flutter: ^1.10.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
