name: zimfarmlink
description: A smart farming coordination app for Zimbabwean agriculture.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  sqlite3_flutter_libs: ^0.5.15
  drift: ^2.15.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  ffi: ^2.1.0 
  path: ^1.9.0

  # State management
  provider: ^6.1.2

  # HTTP & JSON
  http: ^1.2.0

  # Local storage for offline mode
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Offline connectivity & caching
  connectivity_plus: ^5.0.2
  flutter_cache_manager: ^3.3.1

  # UI & animations
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0

  # Icons
  flutter_vector_icons: ^2.0.0

  # Optional for AI/chat features
  speech_to_text: ^6.4.0
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile.jpg
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
